// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdRpl2mAI6l1NPSB-eQ2fv2Ki7EGmSfKc',
    appId: '1:260758274056:android:5d2d9db9deb8521bf311bd',
    messagingSenderId: '260758274056',
    projectId: 'project-aura-msg',
    storageBucket: 'project-aura-msg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEeuc_lTK8aHzslFPl2H6_h7xxlIkKGGM',
    appId: '1:260758274056:ios:3b61ad972338d92ff311bd',
    messagingSenderId: '260758274056',
    projectId: 'project-aura-msg',
    storageBucket: 'project-aura-msg.firebasestorage.app',
    androidClientId: '260758274056-6a1m99498nspmqq3c8g3v3m3ao4hkmc8.apps.googleusercontent.com',
    iosClientId: '260758274056-aoioqfno4ta1m7a15q5pgci0c2l50ele.apps.googleusercontent.com',
    iosBundleId: 'com.radlabs.duttaMessengerApp',
  );
}
